### ISSUE TITLE
Improved algorithm for quad index calculation

### ISSUE THREAD

**Issue by korganrivera** [danielveazey/sudokusolver#1]
I recommend you scrap that huge, ugly lookup table, and replace it with this spiffy, tiny one-liner:

quadindex = 3*((9a+b)/27) + ((9a+b)/3)%3

This gives you the following grid:

![image](https://cloud.githubusercontent.com/assets/8421240/8390211/501d1e64-1c4e-11e5-9749-f319ce4f3bba.png)

**Comment by danielveazey** [comment]
fixed in commit https://github.com/danielveazey/sudokusolver/commit/c9d1607a459fac2238c4e6c4342fd105ea3ed986
